# Generated by Django 5.1.4 on 2025-01-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
                ('created', models.DateField()),
                ('dueDate', models.DateField()),
                ('isCompleted', models.BooleanField()),
            ],
        ),
    ]
